- name: Create an ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: nkumar
    instance_type: t2.micro
    security_group: default
    image: ami-6057e21a
    region: us-east-1
    aws_access_key : AKIAI6SRXSPSZCGDV7RQ
    aws_secret_key : 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
  tasks:
    - name: Amazon EC2 | Create Key Pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: /home/avinash/.ssh/id_rsa.pub
    - name: Launch instance
      ec2:
         aws_access_key : "{{ aws_access_key}}"
         aws_secret_key : "{{ aws_secret_key}}"
         key_name : "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
